services:
  db:
    image: postgres:15-alpine
    container_name: rderico-db-dev
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rderico
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: rderico-api-dev
    restart: always
    ports:
      - "5001:3001"
    volumes:
      - ./apps/api:/app
      - ./CATALOGO DE PRODUCTOS NUMERADOS:/app/static/catalog
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/rderico
      - PORT=3001
    depends_on:
      - db

  pos:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: rderico-pos-dev
    restart: always
    ports:
      - "5000:3000"
    environment:
      - VITE_API_URL=http://192.168.1.117:5001

volumes:
  pgdata:
