"""add_position_to_products

Revision ID: 07ac8e13c9ab
Revises: a6785ccb002f
Create Date: 2026-03-19 01:48:07.163175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ac8e13c9ab'
down_revision: Union[str, None] = 'a6785ccb002f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'position')
    # ### end Alembic commands ###
