"""fix_missing_ticket_columns

Revision ID: 856fedc33ddc
Revises: 104e94a48531
Create Date: 2026-03-17 00:41:01.159525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '856fedc33ddc'
down_revision: Union[str, None] = '104e94a48531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('cash_session_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('captured_by_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('cashed_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'employees', ['captured_by_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'cash_sessions', ['cash_session_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'employees', ['cashed_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'cashed_by_id')
    op.drop_column('tickets', 'captured_by_id')
    op.drop_column('tickets', 'cash_session_id')
    # ### end Alembic commands ###
