"""Add payment_details to Ticket

Revision ID: da64001fd9d4
Revises: 4525deffedd8
Create Date: 2026-03-13 06:30:59.117332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da64001fd9d4'
down_revision: Union[str, None] = '4525deffedd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('payment_details', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'payment_details')
    # ### end Alembic commands ###
